name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Deps
      run: npm ci
    - name: Tests
      run: npm test
    - name: Compile
      run: npm run compile